enh(feature-switch): fully manage feature switch
centreon/centreon-widget-live-top10-cpu-usage pull request #28
Opened 2021-09-09 13:29 UTC by adr-mo

# Pull Request Template

## Description
Handle fully the feature switch between Resource Status and deprecated monitoring pages

**Fixes** # (issue)

## Type of change

- [ ] Patch fixing an issue (non-breaking change)
- [x] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software

## Target serie

- [ ] 20.04.x
- [x] 20.10.x
- [x] 21.04.x
- [x] 21.10.x (master)

<h2> How this pull request can be tested ? </h2>

See Jira ticket for this

## Checklist

#### Community contributors & Centreon team

- [x] I have followed the **coding style guidelines** provided by Centreon
- [ ] I have commented my code, especially new **classes**, **functions** or any **legacy code** modified. (***docblock***)
- [ ] I have commented my code, especially **hard-to-understand areas** of the PR.
- [x] I have **rebased** my development branch on the base branch (master, maintenance).

2021-09-10 07:51 UTC, jeremyjaouen approved these changes

2021-09-10 07:52 UTC, jeremyjaouen requested changes

2021-09-10 07:52 UTC, jeremyjaouen commented on live-top10-cpu-usage/index.php
> +        ? '/centreon/main.php?p=20201&o=svcd&host_name='
Can you use $centreonWebPath as you did here https://github.com/centreon/centreon-widget-host-monitoring/pull/114/files ?

2021-09-10 07:53 UTC, adr-mo commented on live-top10-cpu-usage/index.php
> +        ? '/centreon/main.php?p=20201&o=svcd&host_name='
yep sure :)

2021-09-10 08:36 UTC, adr-mo commented on live-top10-cpu-usage/index.php
> +        ? '/centreon/main.php?p=20201&o=svcd&host_name='
Done ✅

2021-09-14 08:45 UTC, a-launois approved these changes

2021-09-14 13:05 UTC, jeremyjaouen approved these changes

2021-09-15 08:36 UTC, merged